name: Deploy App

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Debugging
        run: |
         git branch
         git remote 
         git remote get-url origin

      - name: Build React app
        run: |
         npm ci
         npm run build
        
      - name: Switch to deploy branch
        run: git checkout -b deploy
        
      - name: Commit build files
        run: |
         # remove old project files
         find . -type f ! -regex './\(build\|.git\)/.*' -delete

         # move new project files
         cp -r build/* ..
         rm -rf build

         git config user.name "${{ github.triggering_actor }}"
         git config user.email "${{ github.triggering_actor }}@users.noreply.github.com"
         git pull origin deploy
         git add -A
         git commit -m "Deploy ${{ github.sha }}"
         git push -u origin deploy


