name: Deploy App

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        path: project
        
      - name: Build React app
        run: |
         cd project
         npm ci
         npm run build
        
      - name: Switch to deploy branch
        run: git checkout -b deploy
        
      - name: Commit build files
      - run: |
         # remove old project files
         find . -type f ! -regex './project/?.*' -delete

         # move new project files
         (cd project/build && cp * ../..)
         rm -rf project

         git commit -am "Deploy ${{ github.sha }}"
         git push -u origin deploy


